export const actionTypes = {
  ADD_SONG: 'ADD_SONG',
  SHIFT_SONG: 'SHIFT_SONG',
  STATION_PLAYLIST_CONNECTED: 'STATION:PLAYLIST_CONNECTED',
  STATION_PLAYLIST_ERROR: 'STATION:PLAYLIST_ERROR',
  STATION_PLAYLIST_UPDATED: 'STATION:PLAYLIST_UPDATED',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
};
