export const actionTypes = {
  ADD_SONG: 'ADD_SONG',
  SHIFT_SONG: 'SHIFT_SONG',
  STATION_PLAYLIST_CONNECTED: 'STATION_PLAYLIST_CONNECTED',
  STATION_PLAYLIST_ERROR: 'STATION_PLAYLIST_ERROR',
  STATION_PLAYLIST_UPDATED: 'STATION_PLAYLIST_UPDATED',
};
