export const actionTypes = {
  ADD_SONG: 'ADD_SONG',
  SHIFT_SONG: 'SHIFT_SONG',
  STATION_PLAYLIST_CONNECTED: 'STATION:PLAYLIST_CONNECTED',
  STATION_PLAYLIST_ERROR: 'STATION:PLAYLIST_ERROR',
  STATION_PLAYLIST_UPDATED: 'STATION:PLAYLIST_UPDATED',
  STATION_GET_STATION_BY_ID_CONNECTED: 'STATION:GET_STATION_BY_ID_CONNECTED',
  STATION_GET_STATION_BY_ID_ERROR: 'STATION:GET_STATION_BY_ID_ERROR',
  STATION_GET_STATION_BY_ID_UPDATED: 'STATION:GET_STATION_BY_ID_UPDATED',
};
