export const stationTypes = {
  STATION_GET_STATION_BY_ID_CONNECTED: 'STATION:GET_STATION_BY_ID_CONNECTED',
  STATION_GET_STATION_BY_ID_ERROR: 'STATION:GET_STATION_BY_ID_ERROR',
  STATION_GET_STATION_BY_ID_UPDATED: 'STATION:GET_STATION_BY_ID_UPDATED',
  STATION_GET_STATION_BY_ID_CLOSED: 'STATION:GET_STATION_BY_ID_CLOSED',
};
