export const stationsListActionTypes = {
  STATIONS_LIST_UPDATE: 'STATIONS_BROWSER:LIST_UPDATED',
  STATIONS_LIST_CONNECTED: 'STATIONS_BROWSER:LIST_CONNECTED',
  STATIONS_LIST_ERROR: 'STATIONS_BROWSER:LIST_ERROR',
  STATIONS_LIST_CLOSED: 'STATIONS_BROWSER:LIST_CLOSED',
  STATION_GET_STATION_BY_ID_CONNECTED: 'STATION:GET_STATION_BY_ID_CONNECTED',
  STATION_GET_STATION_BY_ID_ERROR: 'STATION:GET_STATION_BY_ID_ERROR',
  STATION_GET_STATION_BY_ID_UPDATED: 'STATION:GET_STATION_BY_ID_UPDATED',
  STATION_GET_STATION_BY_ID_CLOSED: 'STATION_GET_STATION_BY_ID_CLOSED',
};
