export const actionTypes = {
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  ADD_FAVORITE: 'ADD_FAVORITE',
  GET_NEWEST_FAVORITE_LIST: 'GET_NEWEST_FAVORITE_LIST',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
};
